# Form implementation generated from reading ui file 'uninstall_flatpak.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess


class Ui_Uninstall_Flatpak(object):
    def setupUi(self, Uninstall_Flatpak):
        Uninstall_Flatpak.setObjectName("Uninstall_Flatpak")
        Uninstall_Flatpak.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/256x256.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Uninstall_Flatpak.setWindowIcon(icon)
        self.pushButton_yes_user = QtWidgets.QPushButton(parent=Uninstall_Flatpak)
        self.pushButton_yes_user.setGeometry(QtCore.QRect(582, 510, 111, 41))
        self.pushButton_yes_user.setObjectName("pushButton_yes_user")
        self.pushButton_yes_system = QtWidgets.QPushButton(parent=Uninstall_Flatpak)
        self.pushButton_yes_system.setGeometry(QtCore.QRect(432, 510, 111, 41))
        self.pushButton_yes_system.setObjectName("pushButton_yes_system")
        self.lineEdit = QtWidgets.QLineEdit(parent=Uninstall_Flatpak)
        self.lineEdit.setGeometry(QtCore.QRect(84, 180, 611, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Uninstall_Flatpak)
        self.label.setGeometry(QtCore.QRect(90, 40, 601, 91))
        self.label.setObjectName("label")
        self.pushButton_no = QtWidgets.QPushButton(parent=Uninstall_Flatpak)
        self.pushButton_no.setGeometry(QtCore.QRect(280, 510, 111, 41))
        self.pushButton_no.setObjectName("pushButton_no")

        self.retranslateUi(Uninstall_Flatpak)
        self.pushButton_no.clicked.connect(Uninstall_Flatpak.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Uninstall_Flatpak)

    def retranslateUi(self, Uninstall_Flatpak):
        _translate = QtCore.QCoreApplication.translate
        Uninstall_Flatpak.setWindowTitle(_translate("Uninstall_Flatpak", "Dialog"))
        self.pushButton_yes_user.setText(_translate("Uninstall_Flatpak", "确定（用户级）"))
        self.pushButton_yes_system.setText(_translate("Uninstall_Flatpak", "确定（系统级）"))
        self.lineEdit.setText(_translate("Uninstall_Flatpak", "修改此处文字修改为你要卸载的软件名称（支持多个，用空格隔开）"))
        self.label.setText(_translate("Uninstall_Flatpak", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:700;\">卸载</span></p></body></html>"))
        self.pushButton_no.setText(_translate("Uninstall_Flatpak", "取消"))

    def user_button_clicked(self):
        self.input_text = self.lineEdit.text()
        self.option = "-y -u --force-remove --delete_data"
        result = subprocess.run(
            ["flatpak uninstall", self.input_text, self.option],
            capture_output = True,
            text = True,
            check = True
        )
        print(result.stdout)
        global exit_code
        exit_code = result.returncode
        self.Ui_Uninstall_Flatpak.reject()
    def system_button_clicked(self):
        self.input_text = self.lineEdit.text()
        self.option = "-y -u --force-remove --delete_data"
        result = subprocess.run(
            ["flatpak uninstall", self.input_text, self.option],
            capture_output = True,
            text = True,
            check = True
        )
        print(result.stdout)
        global exit_code
        exit_code = result.returncode
        self.Ui_Uninstall_Flatpak.reject()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Uninstall_Flatpak = QtWidgets.QDialog()
    ui = Ui_Uninstall_Flatpak()
    ui.setupUi(Uninstall_Flatpak)
    Uninstall_Flatpak.show()
    sys.exit(app.exec())
